import { DiffReport, DiffReportSchema, FileChange, RiskLevel, PlanAlignment } from './types/DiffLens.js';
import { AgentArtifact } from './types/Agent.js';
import { safeResolveForWrite } from '../shared/SafeResolve.js';
import { atomicWrite } from '../shared/AtomicWrite.js';

/**
 * Motor de visualização e auditoria de mudanças.
 */
export class DiffLens {
  private readonly CRITICAL_FILES = [
    '.env',
    'package.json',
    'src/shared/SafeResolve.ts',
    'src/infrastructure/git/WorktreeManager.ts',
  ];

  /**
   * Gera um relatório estruturado a partir dos artefatos consolidados.
   */
  async generateReport(taskId: string, artifacts: AgentArtifact[]): Promise<DiffReport & { ok: boolean }> {
    // Validação de entrada mínima
    if (!taskId) {
      throw new Error('taskId is required for generating audit report.');
    }

    const warnings: string[] = [];
    if (artifacts.length === 0) {
      warnings.push('No artifacts found for this task.');
    }

    let globalRisk: RiskLevel = 'LOW';
    let alignment: PlanAlignment = 'ALIGNED';
    const fileChanges: FileChange[] = [];

    for (const artifact of artifacts) {
      let artifactRisk: RiskLevel = 'LOW';

      // 1. Analisar riscos por tipo de arquivo
      if (artifact.type === 'DIFF') {
        const isCritical = this.CRITICAL_FILES.some(critical => artifact.path.includes(critical));
        if (isCritical) {
          artifactRisk = 'HIGH';
          globalRisk = 'HIGH';
        }
        
        fileChanges.push({
          path: artifact.path,
          reason: 'Code modification detected by @Coder',
          artifactType: 'DIFF',
          riskLevel: artifactRisk,
        });
      }

      // 2. Analisar alinhamento via Review Report
      if (artifact.type === 'REVIEW_REPORT') {
        const content = artifact.content as { status: string } | undefined;
        if (content?.status === 'VIOLATIONS') {
          alignment = 'DIVERGED';
          globalRisk = 'HIGH';
          warnings.push(`Review violations found in ${artifact.path}`);
        }
      }
    }

    const report: DiffReport = {
      taskId,
      summary: `Audit report for task ${taskId}. Found ${fileChanges.length} file changes.`,
      planAlignment: alignment,
      riskLevel: globalRisk,
      fileChanges,
      artifacts,
      warnings,
      createdAt: new Date().toISOString(),
    };

    // Validar saída com Zod
    DiffReportSchema.parse(report);

    return { ...report, ok: globalRisk !== 'HIGH' };
  }

  /**
   * Renderiza o relatório em formato Markdown.
   */
  renderMarkdown(report: DiffReport): string {
    let md = `# GREENFORGE AUDIT — ${report.taskId}\n\n`;
    md += `**Summary:** ${report.summary}\n`;
    md += `**Risk Level:** ${report.riskLevel}\n`;
    md += `**Plan Alignment:** ${report.planAlignment}\n\n`;

    if (report.warnings.length > 0) {
      md += `## ⚠️ Warnings\n`;
      report.warnings.forEach(w => md += `- ${w}\n`);
      md += `\n`;
    }

    md += `## 📝 File Changes\n`;
    if (report.fileChanges.length === 0) {
      md += `No code changes detected.\n`;
    } else {
      md += `| Path | Type | Risk |\n`;
      md += `|------|------|------|\n`;
      report.fileChanges.forEach(fc => {
        md += `| ${fc.path} | ${fc.artifactType} | ${fc.riskLevel} |\n`;
      });
    }
    md += `\n`;

    md += `## 📦 Artifacts Inventory\n`;
    report.artifacts.forEach(a => {
      md += `- **${a.type}**: ${a.path}\n`;
    });

    md += `\n---\n*Generated by DiffLens Engine at ${report.createdAt}*`;

    return md;
  }

  /**
   * Salva o relatório no filesystem de forma segura.
   */
  async saveAuditReport(report: DiffReport, worktreeRoot: string): Promise<string> {
    const fileName = 'GREENFORGE_AUDIT.md';
    const safePath = await safeResolveForWrite(fileName, worktreeRoot);
    
    const content = this.renderMarkdown(report);
    await atomicWrite(safePath, content);
    
    return safePath;
  }
}
